/**
 * A fake provider, for driving the service locally without spending anything.
 *
 * Switched on with `AI_STUB_PROVIDER=1`. Every provider in the registry then
 * answers from here instead of over the network: no key is needed, no quota is
 * spent, and the whole request path — auth, validation, the in-flight lock,
 * storage, the error shapes — can be exercised against the real server.
 *
 * It is not a mock inside a test. The tests stub the provider themselves; this
 * exists so a *running* service can be clicked through, which is the one thing
 * unit tests cannot cover.
 *
 * Two rules keep it from being mistaken for the real thing:
 *
 *   - every answer says so, in the text of the cards themselves;
 *   - `app.js` refuses to boot with this enabled and NODE_ENV=production.
 *
 * ── Asking for a failure ──────────────────────────────────────────────────────
 * A briefing containing `__FAIL:CODE__` comes back as that failure, so the error
 * paths can be driven without waiting for a provider to genuinely rate-limit us:
 *
 *   __FAIL:AI_RATE_LIMIT__      with a detail and retryAfter
 *   __FAIL:AI_QUOTA_EXCEEDED__
 *   __FAIL:AI_MODEL_UNAVAILABLE__
 *   __FAIL:MALFORMED__          a successful call whose body is not JSON
 */

/** Rises with every answer, so a regeneration is visibly a new one. */
let sequence = 0;

const FAIL_PATTERN = /__FAIL:([A-Z_]+)__/;

/** The nonsense this returns, labelled as nonsense. */
const card = (n) => ({
  id: `stub-${n}`,
  title: `Stub insight ${n}`,
  text: `Generated by the stub provider (AI_STUB_PROVIDER=1). Not real advice.`,
  impact: n % 2 === 0 ? "high" : "medium",
});

/**
 * The references a briefing listed, read off its own lines.
 *
 * Every section writes them the same way — `- <ref> · <name> · …` — so this
 * works whatever the prefix. Guessing the shape of a ref instead (`i3f2a`) only
 * ever worked for pricing: staffing and retention build theirs differently, and
 * the mismatch shows up as a section that silently produces no cards.
 */
function refsFromBriefing(briefing) {
  const found = [];
  for (const line of String(briefing).split(/\r?\n/)) {
    const match = /^[-*]\s+(\S+)\s+·/.exec(line.trim());
    if (match && !found.includes(match[1])) found.push(match[1]);
  }
  return found.slice(0, 3);
}

/**
 * The array a section wants its cards in, and the schema of one card.
 *
 * Not always `items`: sales recommendations ask for `recommendations`, and its
 * parser reads that name and nothing else. A stub that always answered `items`
 * produced a reply the section discarded in full — indistinguishable from a model
 * that ignored the schema, and mistaken for one.
 *
 * So the name is read from the schema: the first property that is an array.
 */
function envelopeOf(responseSchema) {
  const properties = responseSchema?.properties ?? {};
  for (const [name, property] of Object.entries(properties)) {
    if (property?.type === "array") {
      return { name, item: property.items ?? null };
    }
  }
  return { name: "items", item: null };
}

/**
 * An object satisfying one card's schema, field by field.
 *
 * Why bother: a section drops any answer missing the fields it needs — pricing
 * wants a `verdict` and at least one line of `advice` before it will show a card.
 * A stub that returns its own shape is therefore indistinguishable from a model
 * that answered badly, and every section would appear to generate nothing.
 *
 * Filling from the schema means each section gets an answer in its own shape
 * without this file knowing anything about any of them.
 */
function fillFromSchema(schema, n, ref) {
  if (!schema?.properties) {
    const plain = card(n);
    return ref ? { ...plain, ref } : plain;
  }

  const value = {};

  for (const [name, property] of Object.entries(schema.properties)) {
    // The reference is the one field that must be real: it is what the section
    // joins on.
    if (name === "ref" && ref) {
      value.ref = ref;
      continue;
    }
    value[name] = valueFor(property, name, n);
  }

  return value;
}

/** One field, by type. Enums take their first option, which is always valid. */
function valueFor(property, name, n) {
  if (Array.isArray(property?.enum) && property.enum.length > 0) {
    return property.enum[0];
  }

  switch (property?.type) {
    case "string":
      return `Stub ${name} ${n} — from AI_STUB_PROVIDER, not real advice.`;
    case "number":
    case "integer":
      // Deliberately above zero: several sections drop a figure of nothing, and
      // a suggested price has to beat the cost to be shown at all.
      return 100 + n;
    case "boolean":
      return true;
    case "array":
      return [valueFor(property.items, name, n)];
    case "object":
      return fillFromSchema(property, n, null);
    default:
      return `Stub ${name} ${n}`;
  }
}

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function generateInsights(_apiKey, { briefing = "", responseSchema } = {}) {
  // A beat, so two overlapping requests really do overlap and the in-flight
  // lock is doing something observable.
  await delay(120);

  const asked = FAIL_PATTERN.exec(briefing);
  if (asked) {
    const code = asked[1];
    if (code === "MALFORMED") {
      return {
        ok: true,
        text: "I'm afraid I can't answer that in JSON.",
        model: "stub-model",
        usage: null,
      };
    }
    return {
      ok: false,
      error: code,
      detail: `Stub provider was asked for ${code}.`,
      ...(code === "AI_RATE_LIMIT" ? { retryAfter: 42 } : {}),
    };
  }

  sequence += 1;
  const first = sequence * 10;

  /**
   * Answer against the references the briefing listed, when it listed any.
   *
   * Sections do not display the model's words alone: most join the answer onto
   * their own figures by a reference (`i3f2a`), and a card only exists when a
   * reference matches. A stub that invents its own ids therefore produces zero
   * cards — which looks exactly like a broken join, and was taken for one.
   *
   * The refs are read back out of the briefing, which is where the section put
   * them, so the join is exercised rather than sidestepped.
   */
  const refs = [...new Set(briefing.match(/\bi[0-9a-z]{4,6}\b/g) ?? [])].slice(0, 3);

  const envelope = envelopeOf(responseSchema);
  const cards = (refs.length ? refs : [null, null]).map((ref, index) =>
    fillFromSchema(envelope.item, first + index, ref),
  );
  const answer = { [envelope.name]: cards };
  return {
    ok: true,
    // Shaped as the caller's schema asked, to the extent the stub can: an object
    // with `items`, which is what all eight sections use.
    text: JSON.stringify(responseSchema ? answer : answer.items),
    model: "stub-model",
    usage: { promptTokens: 100, completionTokens: 50, totalTokens: 150 },
  };
}

/** Any key passes, so the settings screen works with nothing real in it. */
async function verifyKey(_apiKey, model) {
  await delay(40);
  return { ok: true, model: model || "stub-model" };
}

async function listModels() {
  await delay(40);
  return { ok: true, models: ["stub-model", "stub-model-mini", "stub-model-pro"] };
}

async function suggestModels() {
  return ["stub-model-mini", "stub-model-pro"];
}

/**
 * Point every provider in the registry at the stub.
 *
 * Mutates the registry rather than adding a `stub` provider id, deliberately:
 * a new id would appear in the settings catalogue, the frontend would offer it,
 * and a business could end up stored against a provider that does not exist.
 * This way the provider a business has chosen simply answers from here.
 */
function applyStub(providers) {
  for (const provider of Object.values(providers)) {
    provider.generateInsights = generateInsights;
    provider.verifyKey = verifyKey;
    provider.listModels = listModels;
    provider.suggestModels = suggestModels;
  }

  console.warn(
    "[ai] AI_STUB_PROVIDER=1 — every provider is faked. No key is used, " +
      "nothing is spent, and every insight is nonsense.",
  );
}

module.exports = { applyStub, generateInsights, verifyKey };
