/**
 * A fake provider, for driving the service locally without spending anything.
 *
 * Switched on with `AI_STUB_PROVIDER=1`. Every provider in the registry then
 * answers from here instead of over the network: no key is needed, no quota is
 * spent, and the whole request path — auth, validation, the in-flight lock,
 * storage, the error shapes — can be exercised against the real server.
 *
 * It is not a mock inside a test. The tests stub the provider themselves; this
 * exists so a *running* service can be clicked through, which is the one thing
 * unit tests cannot cover.
 *
 * Two rules keep it from being mistaken for the real thing:
 *
 *   - every answer says so, in the text of the cards themselves;
 *   - `app.js` refuses to boot with this enabled and NODE_ENV=production.
 *
 * ── Asking for a failure ──────────────────────────────────────────────────────
 * A briefing containing `__FAIL:CODE__` comes back as that failure, so the error
 * paths can be driven without waiting for a provider to genuinely rate-limit us:
 *
 *   __FAIL:AI_RATE_LIMIT__      with a detail and retryAfter
 *   __FAIL:AI_QUOTA_EXCEEDED__
 *   __FAIL:AI_MODEL_UNAVAILABLE__
 *   __FAIL:MALFORMED__          a successful call whose body is not JSON
 */

/** Rises with every answer, so a regeneration is visibly a new one. */
let sequence = 0;

const FAIL_PATTERN = /__FAIL:([A-Z_]+)__/;

/** The nonsense this returns, labelled as nonsense. */
const card = (n) => ({
  id: `stub-${n}`,
  title: `Stub insight ${n}`,
  text: `Generated by the stub provider (AI_STUB_PROVIDER=1). Not real advice.`,
  impact: n % 2 === 0 ? "high" : "medium",
});

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function generateInsights(_apiKey, { briefing = "", responseSchema } = {}) {
  // A beat, so two overlapping requests really do overlap and the in-flight
  // lock is doing something observable.
  await delay(120);

  const asked = FAIL_PATTERN.exec(briefing);
  if (asked) {
    const code = asked[1];
    if (code === "MALFORMED") {
      return {
        ok: true,
        text: "I'm afraid I can't answer that in JSON.",
        model: "stub-model",
        usage: null,
      };
    }
    return {
      ok: false,
      error: code,
      detail: `Stub provider was asked for ${code}.`,
      ...(code === "AI_RATE_LIMIT" ? { retryAfter: 42 } : {}),
    };
  }

  sequence += 1;
  const first = sequence * 10;

  // Two cards per answer, with ids that never repeat — so "generate more" has
  // something new to append and the deduplication is not what is being tested.
  const answer = { items: [card(first), card(first + 1)] };

  return {
    ok: true,
    // Shaped as the caller's schema asked, to the extent the stub can: an object
    // with `items`, which is what all eight sections use.
    text: JSON.stringify(responseSchema ? answer : answer.items),
    model: "stub-model",
    usage: { promptTokens: 100, completionTokens: 50, totalTokens: 150 },
  };
}

/** Any key passes, so the settings screen works with nothing real in it. */
async function verifyKey(_apiKey, model) {
  await delay(40);
  return { ok: true, model: model || "stub-model" };
}

async function listModels() {
  await delay(40);
  return { ok: true, models: ["stub-model", "stub-model-mini", "stub-model-pro"] };
}

async function suggestModels() {
  return ["stub-model-mini", "stub-model-pro"];
}

/**
 * Point every provider in the registry at the stub.
 *
 * Mutates the registry rather than adding a `stub` provider id, deliberately:
 * a new id would appear in the settings catalogue, the frontend would offer it,
 * and a business could end up stored against a provider that does not exist.
 * This way the provider a business has chosen simply answers from here.
 */
function applyStub(providers) {
  for (const provider of Object.values(providers)) {
    provider.generateInsights = generateInsights;
    provider.verifyKey = verifyKey;
    provider.listModels = listModels;
    provider.suggestModels = suggestModels;
  }

  console.warn(
    "[ai] AI_STUB_PROVIDER=1 — every provider is faked. No key is used, " +
      "nothing is spent, and every insight is nonsense.",
  );
}

module.exports = { applyStub, generateInsights, verifyKey };
