const mongoose = require("mongoose");

const { PERIOD_KINDS } = require("../helpers/analyticsPeriods");

/**
 * A generated insight for one business, one closed analytics period, one
 * section — kept for good.
 *
 * Deliberately a different collection from `aiInsightCache`, not a longer TTL on
 * it, because the two answer different questions:
 *
 *   aiInsightCache   "what did we say about today?"      expires after 26h
 *   aiInsights       "what did we say about September?"  never expires
 *
 * September's figures are final. An insight about them does not go stale, so
 * expiring it would mean paying a provider again for the same answer — which is
 * the whole reason this collection exists. `aiInsightCache` stays as it is for
 * the callers that really are about current data: the sales forecast and the
 * offer scheduler.
 *
 * ── Why `promptVersion` is part of the identity ───────────────────────────────
 * With no expiry, a stored answer outlives the prompt that produced it. Without
 * the version in the key, improving a section's prompt from v3 to v4 would serve
 * the v3 answer for ever and the improvement would never be seen. With it, v4 is
 * a different document: the new answer is generated once, and the old one stays
 * readable until it is deliberately removed.
 */

const aiInsightsSchema = new mongoose.Schema(
  {
    // String, not ObjectId, for the same reason as the other models here: the
    // id arrives from the POS API's answer, and casting it would couple this
    // service to that id format. Becomes { type: ObjectId, ref: "Business" }
    // when this moves into khajaGharBackend.
    businessId: {
      type: String,
      required: true,
      index: true,
    },
    adminId: {
      type: String,
      required: true,
    },

    /**
     * Which period this describes. `kind` and `id` together, never a single
     * composite string: a query for "every monthly insight" is then an index
     * prefix rather than a regex.
     */
    periodKind: {
      type: String,
      required: true,
      enum: PERIOD_KINDS,
    },
    periodId: {
      type: String,
      required: true,
    },
    /**
     * The period's own bounds, copied from the registry at write time.
     *
     * Denormalised on purpose. It lets the newest periods be listed by date
     * without parsing ids in the database, and it records which window the
     * answer actually described — so a later change to a period's definition
     * cannot silently relabel insights already generated under the old one.
     */
    periodStart: {
      type: Date,
      required: true,
    },
    periodEnd: {
      type: Date,
      required: true,
    },

    /** "pricing", "slow-items", … — the section as the route names it. */
    section: {
      type: String,
      required: true,
    },
    /** The prompt that produced this. Part of the identity; see above. */
    promptVersion: {
      type: String,
      required: true,
      default: "v1",
    },

    /**
     * The cards, as their own array rather than inside the answer blob.
     *
     * This is what makes "generate more" a single atomic `$push` instead of a
     * read, a merge and a write — two tabs appending at once would otherwise
     * each write the list they read, and one batch would vanish.
     */
    items: {
      type: [mongoose.Schema.Types.Mixed],
      default: [],
    },
    /**
     * Anything else the section's schema returned — `windows`, `reason`.
     *
     * Kept apart from `items` so appending cannot disturb it, and shapeless
     * because each section asks the model for a different answer.
     */
    extra: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    /**
     * The figures the answer was based on — order count, revenue, items sold.
     *
     * Supplied by the caller, which is the side that read the reports. Stored so
     * a stored insight stays explicable months later ("based on 1,240 orders"),
     * and so an odd-looking answer can be checked against what it was given
     * rather than guessed about.
     */
    basis: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    /** The model that wrote it, as the provider reported it back. */
    model: {
      type: String,
      default: null,
    },
    /** Which provider answered, so a stored insight can say where it came from. */
    provider: {
      type: String,
      default: null,
    },
    /**
     * The provider and model configured when this was written.
     *
     * Not used to invalidate anything — a closed period's insight stays valid
     * whoever wrote it — but it is what lets the UI say "generated by Gemini
     * Flash" and what makes a regeneration under a new model explicable.
     */
    settingsModel: {
      type: String,
      default: null,
    },

    /** When the first answer was written. Not moved by a housekeeping write. */
    generatedAt: {
      type: Date,
      required: true,
    },
    /** Bumped by each regeneration, so "how often is this being redone" is visible. */
    revision: {
      type: Number,
      default: 1,
    },
    lastRegeneratedAt: {
      type: Date,
      default: null,
    },

    /** How many "generate more" batches have been added, the first included. */
    batches: {
      type: Number,
      default: 1,
    },
    /** The model had nothing further to add; asking again would pay for silence. */
    noMore: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  },
);

/**
 * One answer per business, period, section and prompt version.
 *
 * Also the read path: a compound index serves queries on its own prefix, so
 * this one index answers "every section for this business and period" and
 * "every monthly insight for this business" as well. No second index needed for
 * the page load.
 */
aiInsightsSchema.index(
  { businessId: 1, periodKind: 1, periodId: 1, section: 1, promptVersion: 1 },
  { unique: true },
);

/**
 * For the period picker: which periods this business has insights for, newest
 * first. `periodId` sorts lexicographically for months and years but not across
 * kinds, which is why this sorts on the date instead.
 */
aiInsightsSchema.index({ businessId: 1, periodKind: 1, periodStart: -1 });

/** The shape that leaves the server, matching what the frontend already reads. */
aiInsightsSchema.methods.formatted = function () {
  return {
    period: { kind: this.periodKind, id: this.periodId },
    section: this.section,
    promptVersion: this.promptVersion,
    items: this.items ?? [],
    ...(this.extra ?? {}),
    basis: this.basis ?? null,
    model: this.model,
    provider: this.provider,
    generatedAt: this.generatedAt?.toISOString() ?? null,
    revision: this.revision,
    batches: this.batches,
    noMore: this.noMore,
    /** Nothing was spent answering this request. */
    stored: true,
  };
};

const AIInsights = mongoose.model("AIInsights", aiInsightsSchema);
module.exports = AIInsights;
